name: ci

on:
  workflow_dispatch:
    inputs:
      openstack_version:
        description: 'Openstack Release Name'
        required: true
  push:

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: build image 
        run: |
          bash build.sh
        env:
          OPENSTACK_VERSION: '${{ github.event.inputs.openstack_version }}'
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: /home/runner/octavia/diskimage-create/amphora-x64-haproxy.qcow2
